[project]
name = "hyprui"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "pywebview[gtk]>=6.1",
    "rich>=14.2.0",
    "tomlkit>=0.13.3",
]
